In this file we construct the balance test dataset

The balance test dataset comes from `More Power to the People`

Here we change the definition of the treatment variable - expand the number of parishes

Then we join our outcome variables, unemployment, income, wealth, gini coefficients for income and wealth. (So we need to find these results first.)

In [25]:
import pandas as pd
import pathlib

root = pathlib.Path.cwd().parent

df = pd.read_stata(root / "data/balance-tests/data Figure 2 and Table A2.dta")

df.columns

Index(['parish_name', 'parish_code', 'county_id', 'year', 'iline',
       'forw_iline', 'iline_owl', 'lstrikes', 'lstrikesoff', 'lstrikesdef',
       'irail', 'lstrikingworkers', 'shc1', 'shc2', 'shc3', 'shc4', 'shc5',
       'shc6', 'shc7', 'llabforce'],
      dtype='object')

In [26]:
treated_parishes = pd.read_excel(root / "data/parishes/treated_parishes.xlsx")

treated_parishes["treated"] = treated_parishes["iline"]

treated_parishes = treated_parishes.drop(["iline", "parish_name", "parish_name_lower"], axis=1)

df = df.merge(treated_parishes, how = "left", on = "parish_code")

df["treated"] = df["treated"].fillna(0)

In [27]:
df

,parish_name,parish_code,county_id,year,iline,forw_iline,iline_owl,lstrikes,lstrikesoff,lstrikesdef,...,lstrikingworkers,shc1,shc2,shc3,shc4,shc5,shc6,shc7,llabforce,treated
0,EDS FÖRSAMLING AB LÄN,11401000,1,1890.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,NaN,2.027027,7.094595,3.378378,5.743243,13.175675,4.391892,64.189186,551.342896,0.0
1,EDS FÖRSAMLING AB LÄN,11401000,1,1900.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,1.941748,9.061488,4.207120,5.501618,9.708737,9.385114,60.194176,556.834473,0.0
2,EDS FÖRSAMLING AB LÄN,11401000,1,1910.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,2.484472,11.490684,6.832298,2.484472,10.559006,10.869565,55.279507,563.121155,0.0
3,EDS FÖRSAMLING AB LÄN,11401000,1,1920.0,0.0,0.0,1.0,0.000000,0.000000,0.0,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,HAMMARBY FÖRSAMLING AB LÄN,11402000,1,1890.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,NaN,2.008032,10.040161,5.622490,10.040161,8.032128,5.220884,59.036140,541.610046,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9959,JUKKASJÄRVI FÖRSAMLING,258401000,25,1920.0,0.0,0.0,1.0,179.175949,179.175949,0.0,...,698.007568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
9960,KARESUANDO FÖRSAMLING,258403000,25,1890.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,NaN,0.290698,1.162791,0.000000,0.193798,4.166667,1.162791,93.023262,651.914734,0.0
9961,KARESUANDO FÖRSAMLING,258403000,25,1900.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,1.398601,2.797203,0.000000,0.000000,9.440559,7.342658,79.020981,559.471130,0.0
9962,KARESUANDO FÖRSAMLING,258403000,25,1910.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.982801,3.439803,0.491400,0.982801,15.970516,3.194103,74.938576,596.100525,0.0
9963,KARESUANDO FÖRSAMLING,258403000,25,1920.0,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0